### ISSUE TITLE
Text encoding option should be added

### ISSUE THREAD

**Issue by Dionicio3** [Illidanz/ndstextgen#2]
I noticed that this only supports UTF-8 text, when the large majority of NFTR fonts I've seen are either UTF-16LE or SHIFT-JIS. Because of this, I'm unable to type anything outside of basic ASCII using this.

**Comment by Illidanz** [comment]
This should be fixed in 1.7.0

If the font you're using doesn't use the shift_jis encoding, you can use the new encoding parameter to set for example `--encoding utf8`
